### ISSUE TITLE
KeyError: 'beamng' 

### ISSUE THREAD

**Issue by RoboticistAbdulrahman** [BeamNG/beamng-ros-integration#3]
ubuntu_20@DESKTOP-HKDK1FO:~/catkin_ws$ roslaunch beamng_agent example.launch
... logging to /home/ubuntu_20/.ros/log/f5ac04d6-5549-11ec-a125-00155d7eb7cc/roslaunch-DESKTOP-HKDK1FO-25213.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:35383/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.13

NODES
  /
    control (beamng_agent/control.py)

auto-starting new master
process[master]: started with pid [25221]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f5ac04d6-5549-11ec-a125-00155d7eb7cc
process[rosout-1]: started with pid [25231]
started core service [/rosout]
process[control-2]: started with pid [25234]
Traceback (most recent call last):
  File "/home/ubuntu_20/catkin_ws/devel/lib/beamng_agent/control.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/ubuntu_20/catkin_ws/src/beamng-ros-integration/beamng_agent/scripts/control.py", line 82, in <module>
    main()
  File "/home/ubuntu_20/catkin_ws/src/beamng-ros-integration/beamng_agent/scripts/control.py", line 75, in main
    VehicleControl(argv[1])
  File "/home/ubuntu_20/catkin_ws/src/beamng-ros-integration/beamng_agent/scripts/control.py", line 19, in __init__
    params = rospy.get_param("beamng")
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 467, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 123, in __getitem__
    raise KeyError(key)
KeyError: 'beamng'
[control-2] process has died [pid 25234, exit code 1, cmd /home/ubuntu_20/catkin_ws/devel/lib/beamng_agent/control.py ego_vehicle __name:=control __log:=/home/ubuntu_20/.ros/log/f5ac04d6-5549-11ec-a125-00155d7eb7cc/control-2.log].
log file: /home/ubuntu_20/.ros/log/f5ac04d6-5549-11ec-a125-00155d7eb7cc/control-2*.log
^C[rosout-1] killing on exit
^C[master] killing on exit
^Cshutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by RoboticistAbdulrahman** [comment]
i found that this error may not be an error, i just need to run `roslaunch beamng_control example.py` 1st, then  `roslaunch beamng_agent example.py`
